services:
  api:
    build:
      context: .
    container_name: writewinged_api
    restart: unless-stopped

    dns:
      - 8.8.8.8
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # No 'networks' defined here—Docker will create a default one that works

