"""modify document relations

Revision ID: 222c5bdf119c
Revises: a6a6a0ea4810
Create Date: 2026-01-30 12:49:49.388479

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '222c5bdf119c'
down_revision: Union[str, Sequence[str], None] = 'a6a6a0ea4810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
