"""add contribution requests table

Revision ID: 8dddd4d78403
Revises: a38924a1f3fe
Create Date: 2026-08-08 04:08:46.842253

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8dddd4d78403'
down_revision: Union[str, Sequence[str], None] = 'a38924a1f3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='contribution_request_status', native_enum=False), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contribution_requests_document_id'), 'contribution_requests', ['document_id'], unique=False)
    op.create_index(op.f('ix_contribution_requests_user_id'), 'contribution_requests', ['user_id'], unique=False)
    op.create_index('uq_contribution_request_pending_document_user', 'contribution_requests', ['document_id', 'user_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_contribution_request_pending_document_user', table_name='contribution_requests', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_contribution_requests_user_id'), table_name='contribution_requests')
    op.drop_index(op.f('ix_contribution_requests_document_id'), table_name='contribution_requests')
    op.drop_table('contribution_requests')
    # ### end Alembic commands ###
