"""modify_user_roles

Revision ID: 9ddb53506646
Revises: 375ced765992
Create Date: 2025-12-10 14:11:28.370442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ddb53506646'
down_revision: Union[str, Sequence[str], None] = '375ced765992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('USER', 'ADMIN', name='role_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'writer'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='role_enum', native_enum=False),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False,
               existing_server_default=sa.text("'writer'::character varying"))
    # ### end Alembic commands ###
