"""modify contribution field name

Revision ID: a6a6a0ea4810
Revises: 4d976e0890dc
Create Date: 2026-01-30 06:44:43.496609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6a6a0ea4810'
down_revision: Union[str, Sequence[str], None] = '4d976e0890dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('contributions', 'created_At')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('created_At', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('contributions', 'created_at')
    # ### end Alembic commands ###
