"""add versions model and relations

Revision ID: c1d6b108456c
Revises: 9b0935765482
Create Date: 2026-01-22 15:33:21.875063

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c1d6b108456c'
down_revision: Union[str, Sequence[str], None] = '9b0935765482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('change_summary', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_author_id'), 'versions', ['author_id'], unique=False)
    op.create_index(op.f('ix_versions_document_id'), 'versions', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('published_version_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('draft_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_draft_version', 'documents', 'versions', ['draft_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_published_version', 'documents', 'versions', ['published_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_published_version', 'documents', type_='foreignkey')
    op.drop_constraint('fk_draft_version', 'documents', type_='foreignkey')
    op.drop_column('documents', 'draft_version_id')
    op.drop_column('documents', 'published_version_id')
    op.drop_index(op.f('ix_versions_document_id'), table_name='versions')
    op.drop_index(op.f('ix_versions_author_id'), table_name='versions')
    op.drop_table('versions')
    # ### end Alembic commands ###
