"""add proposals table

Revision ID: c8c29d400e28
Revises: 222c5bdf119c
Create Date: 2026-02-08 11:11:24.999868

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8c29d400e28'
down_revision: Union[str, Sequence[str], None] = '222c5bdf119c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('base_version_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='proposal_state', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['base_version_id'], ['versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_author_id'), 'proposals', ['author_id'], unique=False)
    op.create_index(op.f('ix_proposals_document_id'), 'proposals', ['document_id'], unique=False)
    op.drop_constraint(op.f('contributions_document_id_fkey'), 'contributions', type_='foreignkey')
    op.create_foreign_key(None, 'contributions', 'documents', ['document_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.create_foreign_key(op.f('contributions_document_id_fkey'), 'contributions', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_proposals_document_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_author_id'), table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
