"""modify versions model

Revision ID: dd1b8cbf7d73
Revises: c1d6b108456c
Create Date: 2026-01-22 15:38:16.021983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd1b8cbf7d73'
down_revision: Union[str, Sequence[str], None] = 'c1d6b108456c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versions', 'change_summary')
    op.drop_column('versions', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('label', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('versions', sa.Column('change_summary', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
